package com.bangersoul.aivance.core.data.company

import android.content.Context
import com.bangersoul.aivance.core.common.enums.RemotePolicy
import com.bangersoul.aivance.core.common.model.CompanyCatalogEntry
import com.bangersoul.aivance.core.common.model.JobSearchFilter
import kotlinx.serialization.json.Json
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Bundled remote-company catalog (R-02).
 *
 * Parses the `company_catalog.json` asset snapshot generated by
 * `refresh_company_catalog.py` (remoteintech/remote-jobs dataset, ISC-licensed)
 * once, then serves two jobs:
 *
 *  1. **Discovery filtering** — [accepts] decides whether a listing's company
 *     satisfies the catalog filter dimensions of [JobSearchFilter] (remote
 *     policy, tech stack). Listings from companies not in the catalog fail
 *     catalog-filtered searches on purpose: the app can't verify their policy
 *     or stack, so it doesn't claim it does.
 *  2. **Company enrichment** — [findByName]/[findByDomain] resolve the catalog
 *     entry shown on the company detail screen (policy badge, size, region,
 *     technologies, careers URL).
 *
 * Parsing is a pure function ([parse]), so the catalog is fully unit-testable
 * from JSON without Android resources; the [Context] overload only exists for
 * the DI asset load.
 */
@Singleton
class CompanyCatalog private constructor(
    private val entriesByName: Map<String, CompanyCatalogEntry>,
    private val entriesByDomain: Map<String, CompanyCatalogEntry>
) {

    val size: Int get() = entriesByName.size

    /** Case/normalization-insensitive lookup by company name. */
    fun findByName(name: String): CompanyCatalogEntry? =
        entriesByName[CompanyCatalogEntry.normalizeName(name)]

    /** Lookup by registry domain — accepts full URLs or bare hostnames. */
    fun findByDomain(domain: String): CompanyCatalogEntry? {
        val key = CompanyCatalogEntry.extractDomain(domain) ?: return null
        return entriesByDomain[key]
    }

    /**
     * True when [companyName] satisfies the catalog filter dimensions of
     * [filter] (remote policy + technologies). Always true when neither
     * dimension is set. Unknown companies fail only when a dimension is set.
     */
    fun accepts(companyName: String, filter: JobSearchFilter): Boolean {
        if (filter.remotePolicy == null && filter.technologies.isEmpty()) return true
        val entry = findByName(companyName) ?: return false

        filter.remotePolicy?.let { policy ->
            if (!matchesPolicy(entry, policy)) return false
        }

        if (filter.technologies.isNotEmpty()) {
            val terms = filter.technologies.map { it.trim().lowercase() }
                .filter { it.isNotBlank() }
            if (terms.isNotEmpty() && terms.none { entry.technologies.contains(it) }) return false
        }
        return true
    }

    private fun matchesPolicy(entry: CompanyCatalogEntry, policy: RemotePolicy): Boolean {
        return when (policy) {
            // Distributed-first bucket: both signals mean the same thing.
            RemotePolicy.FULLY_REMOTE, RemotePolicy.REMOTE_FIRST ->
                entry.policy == RemotePolicy.FULLY_REMOTE || entry.policy == RemotePolicy.REMOTE_FIRST
            RemotePolicy.REMOTE_FRIENDLY -> entry.policy == RemotePolicy.REMOTE_FRIENDLY
            RemotePolicy.HYBRID -> entry.policy == RemotePolicy.HYBRID
            RemotePolicy.UNKNOWN -> false
        }
    }

    companion object {
        private val json = Json { ignoreUnknownKeys = true }

        fun parse(jsonString: String): List<CompanyCatalogEntry> =
            json.decodeFromString<List<CompanyCatalogEntry>>(jsonString)

        fun fromJson(jsonString: String): CompanyCatalog =
            build(parse(jsonString))

        fun fromAsset(context: Context): CompanyCatalog {
            val text = context.assets.open(ASSET_NAME)
                .bufferedReader()
                .use { it.readText() }
            return fromJson(text)
        }

        internal fun build(entries: List<CompanyCatalogEntry>): CompanyCatalog =
            CompanyCatalog(
                entriesByName = entries.associateBy { CompanyCatalogEntry.normalizeName(it.name) },
                entriesByDomain = entries.mapNotNull { entry ->
                    entry.domain?.let { it to entry }
                }.toMap()
            )

        private const val ASSET_NAME = "company_catalog.json"
    }
}
