version: '3.8'

services:
  android-emulator:
    image: budtmo/docker-android:emulator_11.0
    container_name: aivance-docker-emulator
    privileged: true
    devices:
      - "/dev/kvm:/dev/kvm"
    ports:
      - "6080:6080" # noVNC Web Browser Access (http://<IP>:6080)
      - "5554:5554"
      - "5555:5555" # ADB Connection Port
      - "5900:5900" # VNC / RDP Access Port
    environment:
      - DEVICE=Nexus 5X
      - WEB_VNC=true
      - WEB_VNC_PORT=6080
      - APPIUM=false
    restart: unless-stopped
